### ISSUE TITLE
关于谱面使用

### ISSUE THREAD

**Issue by Moyikc** [Fsu0413/RMEssentials#6]
请问可以提供谱面解密的思路吗，想转到ipad上玩。
小白一枚，不懂加密，从零研究了半天，感觉像是aes加密，16位key应该在本地，奈何不懂逆向，装了个jadx胡乱搜了很久也没定位到关键地方。不知道可以提供下大致思路吗。

**Comment by Fsu0413** [comment]
解包数据不是我提供的，我也不知道，我也不会逆向
目前解密密钥我也拿不到

这个issue先开着吧，等解包数据有了我再更新

**Comment by Moyikc** [comment]
感谢，期待更新！

**Comment by GirlKiller512** [comment]
感觉像 Base64 编码

**Comment by Fsu0413** [comment]
> 感觉像 Base64 编码

确实像，但是base64之后还有啥不太清楚，只解码base64后是乱码

**Comment by Fsu0413** [comment]
https://www.dreamimd.com/p/9829
